# Generated by Django 2.2 on 2019-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20190421_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facepath',
            name='path',
            field=models.CharField(max_length=200, verbose_name='图片路径'),
        ),
    ]
